### ISSUE TITLE
Given ZXPSignCmd bin doesn't work on Debian 9

### ISSUE THREAD

**Issue by Lilipi** [codearoni/zxp-provider#13]
Hi,
I'm trying to use your module on a Debian 9, and it doesn't work.
It seems that there is a problem with given bin : 
![image](https://user-images.githubusercontent.com/7223024/61522191-28135680-aa12-11e9-8d73-88e864fb33aa.png)

Any idea please ?

Thanks

**Comment by codearoni** [comment]
ZxpSignCmd is only designed to support Windows and OSX. The bins don't work at all on Linux. This isn't a "me" thing, it's an Adobe thing. And until they get CC Suite running on Linux, I doubt we'll ever see a working ZxpSignCmd for it. 

I encountered this issue years ago when I was setting up a CI env for this module. I have to disable certain tests from running on Linux. My advice would be to build your extensions on a legit Mac, if you want a true *nix like environment. Hope this helps.
