### ISSUE TITLE
Add postinstall command to set permissions on OSX

### ISSUE THREAD

**Issue by codearoni** [codearoni/zxp-provider#6]
/bin/osx/ZXPSignCmd needs permissions set to 644 after the installation of the module has taken place a given Mac.

**Comment by codearoni** [comment]
@LazyChild Please see PR

**Comment by codearoni** [comment]
@alebianco Please see PR

**Comment by codearoni** [comment]
Setting permissions on the repository itself is meddlesome, especially on cross platform scripts. In place of this, I've set up a postinstall script that will execute immediately after the package is installed. It alters the permissions for the osx binary and it only executes on Darwin machines. I think this is the proper way to handle this issue, and it insulates Window users from the changes as well.

**Comment by LazyChild** [comment]
@codearoni Thank you! Yeah this is a better way! When do you expect to merge the PR and publish to npm?

**Comment by codearoni** [comment]
I could do it tonight if it LGTU

**Comment by codearoni** [comment]
Closing issue. Thanks again @LazyChild  and @alebianco !
